# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09f5cb6b01f3d370831ebe4d5547d47addec3897e81ac6521d6e74cde0232dc8df2f4590b9677b4df3d8d3b28f3b3f30268d48b810cc88d6b4343c2ffa90e677

test:
  secret_key_base: ad79c5fd38196eb414e4a5e025a2eda4ad6a5f10836d1a1a519b80a66212d114c0fc36a04286be69f626f8308fc9022f51277d957071dfb31da0292c299295cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
